# Generated by Django 4.2.1 on 2023-05-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellé', models.CharField(default='a ', max_length=100)),
                ('description', models.TextField(default='non definie')),
                ('prix', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('type', models.CharField(choices=[('em', 'emballé'), ('fr', 'Frais'), ('cs', 'Conserve')], default='em', max_length=2)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
    ]
