# Generated by Django 4.2.1 on 2023-05-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_categorie_fournisseur_produitnc_commande_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProduitNC',
        ),
    ]
